# Setup
title: eResearch Guides
tagline: "User Guides for Macquarie University"
description: "Some User Guides"
# url:
baseurl: ""
paginate: 5
permalink: pretty

# About/contact
author:
  name: Gerry Devine
  url: https://twitter.com/mdo
  email: gerry.devine@mq.edu.au

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y
